name=Boardoza TH09C Temperature Sensor
version=1.0.0
author=Eray Eroglu
maintainer=Boardoza <Boardoza.com>
sentence=Library for Boardoza TH09C Temperature Sensor
paragraph=...
category=Sensors
url=*
architectures=*